'use client'

import { ChangeEvent, FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createBrowserSupabaseClient } from '@/lib/supabase-browser'

type Draft={title:string;slug:string;subtitle:string;excerpt:string;body:string;category:string;author:string;cover_image_url:string;content_type:'article'|'video';video_url:string;status:'draft'|'published'}
const initial:Draft={title:'',slug:'',subtitle:'',excerpt:'',body:'',category:'Quick news',author:'Altus Editorial',cover_image_url:'',content_type:'article',video_url:'',status:'draft'}
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')

export default function AdminDashboard(){
 const router=useRouter();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [mode,setMode]=useState<'sign-in'|'create-owner'|'reset'>('sign-in');const [userEmail,setUserEmail]=useState<string|null>(null);const [draft,setDraft]=useState<Draft>(initial);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{const supabase=createBrowserSupabaseClient();supabase.auth.getUser().then(({data})=>setUserEmail(data.user?.email??null))},[])
 const update=(key:keyof Draft,value:string)=>setDraft(current=>({...current,[key]:value}))
 async function authenticate(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');const supabase=createBrowserSupabaseClient();if(mode==='reset'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/admin/reset`});setBusy(false);setMessage(error?error.message:'Password-reset email sent. Open its link, choose a new password, then return here to sign in.');return}if(mode==='create-owner'){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/admin`}});setBusy(false);if(error)return setMessage(error.message);if(data.session)setUserEmail(data.user?.email??null);else setMessage('Check your email once to confirm the owner account, then return here and sign in with this email and password.');return}const {data,error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)return setMessage(error.message==='Invalid login credentials'?'That email and password do not match. Use “Reset password” below if needed.':error.message);setUserEmail(data.user?.email??null)}
 async function uploadImage(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);setMessage('Uploading image…');try{if(!file.type.startsWith('image/'))throw new Error('Choose a JPG, PNG, WebP, or GIF image.');if(file.size>10*1024*1024)throw new Error('Images must be 10MB or smaller.');const supabase=createBrowserSupabaseClient();const extension=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${crypto.randomUUID()}.${extension}`;const {error}=await supabase.storage.from('altus-media').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;const {data}=supabase.storage.from('altus-media').getPublicUrl(path);update('cover_image_url',data.publicUrl);setMessage('Image uploaded and ready.')}catch(error){setMessage(error instanceof Error?error.message:'The image could not be uploaded.')}finally{setBusy(false)}}
 async function publish(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const supabase=createBrowserSupabaseClient();const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)throw new Error('Your session has expired. Please sign in again.');const payload={title:draft.title.trim(),slug:(draft.slug||slugify(draft.title)).trim(),subtitle:draft.subtitle.trim()||null,excerpt:draft.excerpt.trim(),body:draft.body.trim(),category:draft.category.trim(),author:draft.author.trim(),cover_image_url:draft.cover_image_url.trim()||null,content_type:draft.content_type,video_url:draft.content_type==='video'?draft.video_url.trim():null,status:draft.status,published_at:draft.status==='published'?new Date().toISOString():null,author_id:user.id};const {error}=await supabase.from('posts').insert(payload);if(error){if(error.code==='23505'&&error.message.includes('posts_slug_key'))throw new Error(`That URL slug is already used. Change it to something unique, for example "${payload.slug}-update".`);if(error.message.includes('row-level security'))throw new Error('This account is not approved as the Altus editor yet. Tell me the email you used and I will securely grant it editor access.');throw new Error(error.message)}setMessage(draft.status==='published'?`Published to Altus ${draft.content_type==='video'?'Videos':'News'} — check the public site now.`:'Draft saved.');setDraft(initial);router.refresh()}catch(error){const detail=typeof error==='object'&&error&&'message' in error?String(error.message):'Could not save this post.';setMessage(detail)}finally{setBusy(false)}}
 async function signOut(){const supabase=createBrowserSupabaseClient();await supabase.auth.signOut();setUserEmail(null);setMessage('Signed out.')}
 if(!userEmail){const reset=mode==='reset';return <main className="admin-shell"><section className="admin-card"><p className="eyebrow">Altus publishing desk</p><h1>{reset?<>Reset your<br/><em>password.</em></>:mode==='create-owner'?<>Create the<br/><em>owner account.</em></>:<>Sign in to<br/><em>publish.</em></>}</h1><p>{reset?'Use the email address you chose for the Altus owner account.':mode==='create-owner'?'Only use this once. The first confirmed account becomes the Altus editor.':'Use your Altus owner email and password. Email confirmation happens only once when the account is created.'}</p><form onSubmit={authenticate} className="admin-form"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>{!reset&&<label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>}<button className="buy-button" disabled={busy}>{busy?'Please wait…':reset?'Send password-reset email':mode==='create-owner'?'Create owner account':'Sign in'}</button></form>{mode==='sign-in'?<div className="admin-links"><button className="admin-switch" onClick={()=>{setMode('reset');setMessage('')}}>Reset password</button><button className="admin-switch" onClick={()=>{setMode('create-owner');setMessage('')}}>First time? Create the owner account</button></div>:<button className="admin-switch" onClick={()=>{setMode('sign-in');setMessage('')}}>Back to sign in</button>}{message&&<p className="admin-message">{message}</p>}</section></main>}
 return <main className="admin-shell"><section className="admin-head"><div><p className="eyebrow">Altus publishing desk</p><h1>Publish the<br/><em>signal.</em></h1><p>Signed in as {userEmail}</p></div><button onClick={signOut} className="admin-signout">Sign out</button></section><form onSubmit={publish} className="editor-grid"><section className="admin-card editor-main"><label>Headline<input value={draft.title} onChange={e=>{update('title',e.target.value);if(!draft.slug)update('slug',slugify(e.target.value))}} required placeholder="A clear, precise headline"/></label><label>URL slug<input value={draft.slug} onChange={e=>update('slug',slugify(e.target.value))} required placeholder="your-story-url"/></label><label>Subtitle<input value={draft.subtitle} onChange={e=>update('subtitle',e.target.value)} placeholder="Optional supporting line"/></label><label>Summary<textarea value={draft.excerpt} onChange={e=>update('excerpt',e.target.value)} required rows={3} placeholder="What should readers know before they open it?"/></label><label>Story<textarea className="story-editor" value={draft.body} onChange={e=>update('body',e.target.value)} required rows={16} placeholder="Write the story. Separate paragraphs with an empty line."/></label></section><aside className="admin-card editor-side"><label>Post type<select value={draft.content_type} onChange={e=>update('content_type',e.target.value)}><option value="article">Article or quick news</option><option value="video">Video post</option></select></label>{draft.content_type==='video'&&<label>Video link<input type="url" value={draft.video_url} onChange={e=>update('video_url',e.target.value)} required placeholder="YouTube or Vimeo link"/></label>}<label>Category<input value={draft.category} onChange={e=>update('category',e.target.value)} required/></label><label>Byline<input value={draft.author} onChange={e=>update('author',e.target.value)} required/></label><label>Cover image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadImage}/></label>{draft.cover_image_url&&<img className="admin-cover-preview" src={draft.cover_image_url} alt="Selected cover"/>}<label>Or image URL<input type="url" value={draft.cover_image_url} onChange={e=>update('cover_image_url',e.target.value)} placeholder="https://…"/></label><label>Publishing status<select value={draft.status} onChange={e=>update('status',e.target.value)}><option value="draft">Save as draft</option><option value="published">Publish now</option></select></label><button className="buy-button" disabled={busy}>{busy?'Saving…':draft.status==='published'?'Publish now':'Save draft'}</button><p>Website posts publish here. Beehiiv subscriptions and newsletter delivery stay separate.</p>{message&&<p className="admin-message">{message}</p>}</aside></form></main>
}
